name: Radon CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Run image
      uses: abatilo/actions-poetry@v2
      with:
        poetry-version: '1.7.1'

    - name: Install dependencies
      working-directory: api
      run: |
        poetry install

    - name: Run Radon
      run: |
        poetry run radon cc -a -s -na -nb -nc -e 10 LibraryManagement/api